### ISSUE TITLE
Training scripts and results on predcls & sgcls

### ISSUE THREAD

**Issue by jkli-aa** [MCG-NJU/Structured-Sparse-RCNN#6]
Hi, thanks for your nice work :)
Could you provide the training scripts and results on predcls and sgcls? They are two common settings in scene graph generation.

**Comment by tyshiwo1** [comment]
Oh, sorry, I don't feel like I have a perfect solution to these two challenges.

In the section 4.1. of my paper, I mentioned that because our model doesn't contain an object detector in the inference phase, PredCls and SGCls are not suitable for our model.

However, an imperfect substitute I've come up with recently is using a matcher based on IOU to align some object pair predictions with the ground-truth, but this process could introduce some noise into the results.

**Comment by jkli-aa** [comment]
Well, I understand.
Thank you for your quick and kind reply :)
